############################################################
# Dockerfile to run an OrientDB (Graph) Container
############################################################

FROM openjdk:8-jdk-slim

LABEL maintainer "info@orientdb.com"

# Override the orientdb download location with e.g.:
#   docker build -t mine --build-arg ORIENTDB_DOWNLOAD_SERVER=https://repo1.maven.org/maven2/com/orientechnologies/ .
ARG ORIENTDB_DOWNLOAD_SERVER

ENV ORIENTDB_VERSION 3.0.28 
ENV ORIENTDB_DOWNLOAD_MD5 931e22bb22e10af99f18144cbee04551 
ENV ORIENTDB_DOWNLOAD_SHA1 fc9f93773576fbf7493dbe8f8c6b784d0165d028 
ENV ORIENTDB_ROOT_PASSWORD admin

ENV ORIENTDB_DOWNLOAD_URL ${ORIENTDB_DOWNLOAD_SERVER:-https://repo1.maven.org/maven2/com/orientechnologies}/orientdb-community/$ORIENTDB_VERSION/orientdb-community-$ORIENTDB_VERSION.tar.gz

RUN apt update \
    && apt install -y curl wget \
    && rm -rf /var/lib/apt/lists/* \
    && mkdir /orientdb \
    && wget --quiet $ORIENTDB_DOWNLOAD_URL \
    && echo "$ORIENTDB_DOWNLOAD_MD5 *orientdb-community-$ORIENTDB_VERSION.tar.gz" | md5sum -c - \
    && echo "$ORIENTDB_DOWNLOAD_SHA1 *orientdb-community-$ORIENTDB_VERSION.tar.gz" | sha1sum -c - \
    && tar -xvzf orientdb-community-$ORIENTDB_VERSION.tar.gz -C /orientdb --strip-components=1 \
    && apt remove -y curl wget \
    && apt clean -y \
    && apt autoremove -y \
    && rm orientdb-community-$ORIENTDB_VERSION.tar.gz 
    # NO BORRAR LA CARPETA DE BASE DE DATOS
    #&& rm -rf /orientdb/databases/*


ENV PATH /orientdb/bin:$PATH

WORKDIR /orientdb

#COPIAR LA BASE DE DATOS PPR A LA CARPETA databases
COPY ./orientdb/databases/PPR ./databases/PPR
#COPIAR ALGUNAS BASES DE DATOS DE EJEMPLO A databases
#COPY ./orientdb/databases/GOT ./databases/GOT
#COPY ./orientdb/databases/vehiclehistory ./databases/vehiclehistory
#COPY ./orientdb/databases/movieratings ./databases/movieratings
COPY ./orientdb/databases/portico ./databases/portico

VOLUME ["/orientdb/backup", "/orientdb/databases", "/orientdb/config"]

#OrientDb binary y HTTP
EXPOSE 2424 2480

# Default command start the server
ENTRYPOINT ["server.sh"]