GET http://localhost:8000/conceptos

{
  "filter" : {
        "Nombre" : "RELACIONAL"
    },
    "limit" : 2  
}
###
GET http://localhost:8000/conceptos/complejos
###
POST http://localhost:8000/concepto

{
    "Nombre" : "TEST 122"
}
###
PUT http://localhost:8000/concepto

{
    "oldConcepto" : {
        "Nombre" : "TEST122"
    },
    "newConcepto" : {
        "Nombre" : "TEST1222"
    }
}
###
DELETE http://localhost:8000/concepto

{
    "Nombre" : "TEST1222"
}
###
GET http://localhost:8000/concepto/refs

{
    "Nombre" : "POO"
}
###
GET http://localhost:8000/concepto/equivalencias

{
    "Nombre" : "TESTCUATRO"
}
###
POST http://localhost:8000/concepto/equivalencias

{
    "concepto" : {
        "Nombre" : "TESTCUATRO"
    },
    "equivalencia" : {
        "Nombre" : "OTRAEQUIVALENCIAPORAPI",
        "Peso" : 0.5
    }
}
###
DELETE http://localhost:8000/concepto/equivalencias

{
    "concepto" : {
        "Nombre" : "TESTCUATRO"
    },
    "equivalencia" : {
        "Nombre" : "PRUEBA EQUIV",
        "Peso" : 0
    }
}
###
GET http://localhost:8000/relaciones
###
GET http://localhost:8000/docs
###

GET http://localhost:8000/openapi.json
###

GET http://localhost:8000/path

{
    "conceptoInicial" : {
        "Nombre" : "POO"
    },
    "conceptosIncluidos" : [
        "OBJETO",
        "ATRIBUTO",
        "METODO"
    ]
}
###

GET http://localhost:8000/path/depth

{
    "conceptoInicial" : {
        "Nombre" : "POO"
    },
    "depth" : 1
}

###

POST http://localhost:8000/text/check

{
    "texto" : "Los ovjetos son parte del paradigma POO y están formados por métodos y hatributos"
}
###

POST http://localhost:8000/text/tokenize

{
    "texto" : "Una sentencia es verdadera si todo su contenido interno es coherente y real",
    "includeStopWords" : "false"
}